microscope:
  class_name: AutoScriptMicroscope
  module_name: asyncroscopy.instruments.electron_microscope.auto_script
  description: Thermo Fisher Spectra 300 TEM
  host: 127.0.0.1
  port: 9095
digital_twin:
  class_name: DigitalTwin
  module_name: asyncroscopy.instruments.electron_microscope.digital_twin
  description: Software digital twin
devices:
  camera:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.camera
  data:
    module_name: asyncroscopy.data.data
  eds:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.eds
  flucam:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.flucam
  scan:
    module_name: asyncroscopy.instruments.electron_microscope.hardware.scan
  stage:
    module_name: asyncroscopy.instruments.electron_microscope.hardware.stage
tango:
  host: 127.0.0.1
  port: 9094
tiled:
  host: 127.0.0.1
  port: 9091
  acquisition_dir: outputs/tiled_acquisitions
  autostart: true
device_timeout_seconds: 120
